/**
 * Builds src/components/ui/glyphData.ts from game-icons.net silhouettes
 * (CC BY 3.0, https://game-icons.net) plus a few original AXEdex glyphs.
 *
 * The icon package is large, so it is not a project dependency. To refresh:
 *   npm i --no-save @iconify-json/game-icons && node scripts/extract-glyphs.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

export const GLYPHS = [
  // games
  'spades', 'slot-machine', 'rocket-flight', 'ball-pyramid', 'unlit-bomb', 'rolling-dices', 'poker-hand',
  'card-exchange', 'crown-coin', 'dragon-head', 'tiger-head', 'dice-fire', 'on-target', 'tower-flag', 'coinflip', 'ticket',
  // interface
  'house', 'crown', 'present', 'calendar', 'piggy-bank', 'trophy-cup', 'upgrade', 'histogram', 'money-stack', 'coins',
  'achievement', 'fire', 'lightning-arc', 'padlock', 'hourglass',
  // achievements & game art
  'checkered-flag', 'world', 'run', 'comet-spark', 'cut-diamond', 'top-hat', 'sands-of-time', 'muscle-up',
  'laurels-trophy', 'bullseye', 'moon', 'diamond-trophy', 'crystal-ball', 'wizard-face', 'stone-tower', 'death-skull',
  'eagle-emblem', 'cherry', 'clover', 'ringing-bell', 'sparkles', 'star-medal', 'lemon', 'grapes', 'flat-star',
  'jet-fighter', 'airplane-arrival',
]

const root = process.env.ICON_SOURCE ?? 'node_modules'
const set = JSON.parse(readFileSync(join(root, '@iconify-json/game-icons/icons.json'), 'utf8'))

// Original glyphs in the same 512×512 silhouette style.
function roulette() {
  const cx = 256, cy = 256, parts = []
  parts.push(`M${cx} 24a232 232 0 1 1 0 464a232 232 0 1 1 0-464Zm0 44a188 188 0 1 0 0 376a188 188 0 1 0 0-376Z`)
  const n = 16
  for (let i = 0; i < n; i += 2) {
    const a0 = (i / n) * Math.PI * 2, a1 = ((i + 1) / n) * Math.PI * 2
    const p = (r, a) => `${(cx + r * Math.cos(a)).toFixed(1)} ${(cy + r * Math.sin(a)).toFixed(1)}`
    parts.push(`M${p(176, a0)}A176 176 0 0 1 ${p(176, a1)}L${p(112, a1)}A112 112 0 0 0 ${p(112, a0)}Z`)
  }
  parts.push(`M${cx} 164a92 92 0 1 1 0 184a92 92 0 1 1 0-184Zm0 36a56 56 0 1 0 0 112a56 56 0 1 0 0-112Z`)
  parts.push('M244 150h24v212h-24ZM150 244h212v24H150Z')
  parts.push(`M${cx} 226a30 30 0 1 1 0 60a30 30 0 1 1 0-60Z`)
  parts.push('M392 150a26 26 0 1 1 0 52a26 26 0 1 1 0-52Z')
  return parts.map((d) => `<path d="${d}"/>`).join('')
}

function fortuneWheel() {
  const cx = 256, cy = 276, parts = []
  parts.push(`M${cx} ${cy - 216}a216 216 0 1 1 0 432a216 216 0 1 1 0-432Zm0 36a180 180 0 1 0 0 360a180 180 0 1 0 0-360Z`)
  const n = 8
  for (let i = 0; i < n; i += 2) {
    const a0 = (i / n) * Math.PI * 2 - Math.PI / 2, a1 = ((i + 1) / n) * Math.PI * 2 - Math.PI / 2
    const p = (r, a) => `${(cx + r * Math.cos(a)).toFixed(1)} ${(cy + r * Math.sin(a)).toFixed(1)}`
    parts.push(`M${p(164, a0)}A164 164 0 0 1 ${p(164, a1)}L${p(40, a1)}A40 40 0 0 0 ${p(40, a0)}Z`)
  }
  parts.push(`M${cx} ${cy - 26}a26 26 0 1 1 0 52a26 26 0 1 1 0-52Z`)
  for (let i = 0; i < 12; i++) {
    const a = (i / 12) * Math.PI * 2
    const x = cx + 198 * Math.cos(a), y = cy + 198 * Math.sin(a)
    parts.push(`M${x.toFixed(1)} ${(y - 9).toFixed(1)}a9 9 0 1 1 0 18a9 9 0 1 1 0-18Z`)
  }
  parts.push('M216 8h80l-40 78Z')
  return parts.map((d) => `<path d="${d}"/>`).join('')
}

function keno() {
  const parts = ['M96 40h320a56 56 0 0 1 56 56v320a56 56 0 0 1-56 56H96a56 56 0 0 1-56-56V96a56 56 0 0 1 56-56Zm0 36a20 20 0 0 0-20 20v320a20 20 0 0 0 20 20h320a20 20 0 0 0 20-20V96a20 20 0 0 0-20-20Z']
  const filled = new Set([1, 6, 8, 13, 15])
  for (let r = 0; r < 4; r++) for (let c = 0; c < 4; c++) {
    const x = 146 + c * 73, y = 146 + r * 73, i = r * 4 + c
    parts.push(filled.has(i) ? `M${x} ${y - 30}a30 30 0 1 1 0 60a30 30 0 1 1 0-60Z` : `M${x} ${y - 30}a30 30 0 1 1 0 60a30 30 0 1 1 0-60Zm0 14a16 16 0 1 0 0 32a16 16 0 1 0 0-32Z`)
  }
  return parts.map((d) => `<path d="${d}"/>`).join('')
}

const out = {}
for (const name of GLYPHS) {
  const icon = set.icons[name]
  if (!icon) throw new Error(`Missing glyph: ${name}`)
  out[name] = icon.body.replaceAll(' fill="currentColor"', '')
}
out['roulette-wheel'] = roulette()
out['fortune-wheel'] = fortuneWheel()
out['keno-grid'] = keno()

const names = Object.keys(out)
const file = `// Generated by scripts/extract-glyphs.mjs — do not edit by hand.
// Silhouettes from game-icons.net (CC BY 3.0); roulette-wheel, fortune-wheel and keno-grid are original.
export const GLYPH_PATHS = {
${names.map((n) => `  '${n}': ${JSON.stringify(out[n])},`).join('\n')}
} as const

export type GlyphName = keyof typeof GLYPH_PATHS
`
writeFileSync(new URL('../src/components/ui/glyphData.ts', import.meta.url), file)
console.log(`Wrote ${names.length} glyphs, ${Math.round(file.length / 1024)} KB`)
