import type { GlyphName } from './glyphData'
import type { GlyphTone } from './glyphTones'

/** Semantic icon names used across the app, each mapped to a glyph and a colour. */
export const ICON_MAP = {
  // games
  roulette: ['roulette-wheel', 'rose'],
  'blackjack-cards': ['spades', 'emerald'],
  'slot-machine': ['slot-machine', 'pink'],
  rocket: ['rocket-flight', 'cyan'],
  plinko: ['ball-pyramid', 'violet'],
  bomb: ['unlit-bomb', 'orange'],
  'game-die': ['rolling-dices', 'rose'],
  'fortune-wheel': ['fortune-wheel', 'emerald'],
  joker: ['poker-hand', 'sky'],
  'input-numbers': ['keno-grid', 'cyan'],
  'card-exchange': ['card-exchange', 'orange'],
  'diamond-suit': ['crown-coin', 'gold'],
  'dragon-face': ['dragon-head', 'orange'],
  'tiger-face': ['tiger-head', 'gold'],
  'sic-bo': ['dice-fire', 'rose'],
  bullseye: ['on-target', 'violet'],
  castle: ['tower-flag', 'sky'],
  coin: ['coinflip', 'gold'],
  'admission-tickets': ['ticket', 'lime'],
  // interface
  'wrapped-gift': ['present', 'emerald'],
  'spiral-calendar': ['calendar', 'gold'],
  'tear-off-calendar': ['calendar', 'cyan'],
  'money-bag': ['piggy-bank', 'cyan'],
  'glowing-star': ['upgrade', 'violet'],
  trophy: ['trophy-cup', 'gold'],
  crown: ['crown', 'gold'],
  sparkles: ['sparkles', 'gold'],
  house: ['house', 'emerald'],
  'bust-in-silhouette': ['crown', 'gold'],
  'gem-stone': ['cut-diamond', 'cyan'],
  fire: ['fire', 'orange'],
  'bar-chart': ['histogram', 'cyan'],
  'hundred-points': ['lightning-arc', 'violet'],
  'chart-increasing': ['upgrade', 'emerald'],
  coins: ['coins', 'gold'],
  // achievements
  'party-popper': ['checkered-flag', 'emerald'],
  'world-map': ['world', 'cyan'],
  'person-running': ['run', 'emerald'],
  'top-hat': ['top-hat', 'violet'],
  'crescent-moon': ['moon', 'sky'],
  comet: ['comet-spark', 'orange'],
  'money-with-wings': ['money-stack', 'emerald'],
  'flexed-biceps': ['muscle-up', 'rose'],
  'person-mage': ['wizard-face', 'violet'],
  'sports-medal': ['achievement', 'gold'],
  'crystal-ball': ['crystal-ball', 'violet'],
  'laurels-trophy': ['laurels-trophy', 'gold'],
  'diamond-trophy': ['diamond-trophy', 'cyan'],
  // in-game art
  'four-leaf-clover': ['clover', 'lime'],
  'spade-suit': ['spades', 'silver'],
  eagle: ['eagle-emblem', 'gold'],
  skull: ['death-skull', 'rose'],
  cherries: ['cherry', 'rose'],
  bell: ['ringing-bell', 'gold'],
  locked: ['padlock', 'silver'],
  tower: ['stone-tower', 'sky'],
} as const satisfies Record<string, readonly [GlyphName, GlyphTone]>

export type IconName = keyof typeof ICON_MAP
